## Put comments here that give an overall description of what your
## functions do

## makeCacheMatrix: This function creates a list of functions.
## These functions can cache a given matrix and its inverse,
## and calling one of these function can return or change 
## the cached matrix or its inverse.

makeCacheMatrix <- function(x = matrix()) {
  sol <- NULL           #sol will be the inverse of the matrix and it's
                        #reset to NULL everytime makeCacheMatrix is called.
  set <- function(y) {  #set is called when input y is not equal to cached x?
    x <<- y             #Cached x is changed to be the same as the input.
    sol <<- NULL        #The cached inverse is reset to NULL.
  }
  get <- function() {   #get function can be used to get the cached input 
    x                   #matrix x.
  }
  setsolve <- function(solv) {  #setsolve function take the input and cache                                                                                                                                                                           
    sol <<- solv                #it. setsolve function should be called when
  }                             #the inverse is caculated(in cacheSolve or 
                                # elsewhere).
  getsolve <- function() sol    #getsolve function returns the cached inverse
                                #(if ti exists).
  list(set = set, get = get,    #makeCacheMatrix function returns a list of
       setsolve = setsolve,     #functions (with the input matrix cached and
       getsolve = getsolve)     #can cache another matrix sol).
}


## cacheSolve function computes the inverse of the special "matrix" returned
##by makeCacheMatrix above. If the inverse has already been calculated (and 
##the matrix has not changed), then the cachesolve should retrieve the 
##inverse from the cache.

cacheSolve <- function(x, ...) {  # here x should be a list of function
                                  #generated by makeCacheMatrix function
  sol <- x$getsolve()             #get the cached inverse from x
  if(!is.null(sol)) {
    message("getting cached data")
    return(sol)                   #if the inverse has been cached, return it
  }
  data <- x$get()                 #if not, get the orginial input matrix
  sol <- solve(data, ...)         #from x and calculate its inverse
  x$setsolve(sol)                 #then cache the inverse in x
  sol                             #Return a matrix that is the inverse
}
